//! Generates an embedded theme lookup from `themes/**` into OUT_DIR.
//! The generated Rust stays under `target/` and is never committed.

use std::{
    env, fs,
    path::{Path, PathBuf},
};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let themes_root = manifest_dir.join("themes");
    println!("cargo:rerun-if-changed=themes");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("embedded_theme.rs");

    let mut files = Vec::new();
    if themes_root.exists() {
        collect_theme_files(&themes_root, &themes_root, &mut files);
    }
    files.sort();

    let mut source = String::from(
        "// @generated by build.rs — do not edit.\n\
fn embedded_theme(path: &str) -> Option<&'static str> {\n\
    match path {\n",
    );

    for relative in &files {
        let key = relative.replace('\\', "/");
        let include_path = format!("themes/{key}").replace('\\', "/");
        source.push_str(&format!(
            "        \"{key}\" => Some(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{include_path}\"))),\n"
        ));
    }

    source.push_str("        _ => None,\n    }\n}\n");
    fs::write(&dest, source).expect("write embedded_theme.rs");
}

fn collect_theme_files(root: &Path, dir: &Path, out: &mut Vec<String>) {
    let entries = match fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(_) => return,
    };

    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if name.starts_with('.') {
            continue;
        }
        if path.is_dir() {
            collect_theme_files(root, &path, out);
            continue;
        }
        let Some(ext) = path.extension().and_then(|ext| ext.to_str()) else {
            continue;
        };
        if !matches!(ext, "html" | "css" | "js" | "json") {
            continue;
        }
        let Ok(relative) = path.strip_prefix(root) else {
            continue;
        };
        out.push(relative.to_string_lossy().replace('\\', "/"));
    }
}
