[application]

[web.app]

# HTML title tag content
title = "ServerSpot"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = [
  "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/fontawesome.min.css",
  "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/brands.min.css",
]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
